version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: kanban_mysql
    restart: always
    environment:
      MYSQL_DATABASE: kanban_db
      MYSQL_USER: kanban_user
      MYSQL_PASSWORD: kanban_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: kanban_backend
    restart: always
    environment:
      - DEBUG=False
      - SECRET_KEY=your-secret-key-here
      - DATABASE_URL=mysql://kanban_user:kanban_password@mysql:3306/kanban_db
      - ALLOWED_HOSTS=localhost,127.0.0.1,backend
    ports:
      - "8000:8000"
    volumes:
      - ./staticfiles:/app/staticfiles
    depends_on:
      mysql:
        condition: service_healthy
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 kanban_project.wsgi:application"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kanban_frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:8000

  nginx:
    image: nginx:alpine
    container_name: kanban_nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./staticfiles:/staticfiles
    depends_on:
      - backend
      - frontend

volumes:
  mysql_data: